/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as vaultManagerSol from "./VaultManager.sol";
export type { vaultManagerSol };
export type { FollowerRegistry } from "./FollowerRegistry";
export type { Greeting } from "./Greeting";
export type { AUSD } from "./AUSD";
