/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IFusionXRouter } from "./IFusionXRouter";
export type { IaUSD } from "./IaUSD";
export type { VaultManager } from "./VaultManager";
