/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace VaultManager {
  export type VaultLimitsStruct = {
    slippageBps: BigNumberish;
    minLeaderTradeUsd: BigNumberish;
    maxLeaderTradeUsd: BigNumberish;
    minAllocUsd: BigNumberish;
    maxAllocUsd: BigNumberish;
  };

  export type VaultLimitsStructOutput = [
    slippageBps: bigint,
    minLeaderTradeUsd: bigint,
    maxLeaderTradeUsd: bigint,
    minAllocUsd: bigint,
    maxAllocUsd: bigint
  ] & {
    slippageBps: bigint;
    minLeaderTradeUsd: bigint;
    maxLeaderTradeUsd: bigint;
    minAllocUsd: bigint;
    maxAllocUsd: bigint;
  };

  export type VaultConfigStruct = {
    follower: AddressLike;
    leader: AddressLike;
    ausdLocked: BigNumberish;
    ausdAllocated: BigNumberish;
    riskLevel: BigNumberish;
    maxPerTradePct: BigNumberish;
    allowlist: AddressLike[];
    status: BigNumberish;
    limits: VaultManager.VaultLimitsStruct;
  };

  export type VaultConfigStructOutput = [
    follower: string,
    leader: string,
    ausdLocked: bigint,
    ausdAllocated: bigint,
    riskLevel: bigint,
    maxPerTradePct: bigint,
    allowlist: string[],
    status: bigint,
    limits: VaultManager.VaultLimitsStructOutput
  ] & {
    follower: string;
    leader: string;
    ausdLocked: bigint;
    ausdAllocated: bigint;
    riskLevel: bigint;
    maxPerTradePct: bigint;
    allowlist: string[];
    status: bigint;
    limits: VaultManager.VaultLimitsStructOutput;
  };
}

export interface VaultManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "AUSD"
      | "MAX_SLIPPAGE_BPS"
      | "MAX_TRADE_AGE"
      | "MIN_COPY_SCORE"
      | "MIN_SLIPPAGE_BPS"
      | "MIN_TRADE_AUSD"
      | "addToAllowlist"
      | "closePosition"
      | "createVault"
      | "deposit"
      | "dex"
      | "executeCopyTrade"
      | "followerVaults"
      | "getAllowlist"
      | "getFollowerVaults"
      | "getFreeBalance"
      | "getOpenPositions"
      | "getUnrealizedPnL"
      | "getVault"
      | "keeperOf"
      | "latestPrice"
      | "oracle"
      | "owner"
      | "pauseVault"
      | "positions"
      | "removeFromAllowlist"
      | "reopenVault"
      | "resumeVault"
      | "setDex"
      | "setKeeper"
      | "setOracle"
      | "setPrice"
      | "transferOwnership"
      | "vaultId"
      | "vaultPositions"
      | "vaults"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AllowlistAdded"
      | "AllowlistRemoved"
      | "DexSet"
      | "KeeperSet"
      | "OracleSet"
      | "PositionClosed"
      | "PositionOpened"
      | "PriceUpdated"
      | "StrategistResponse"
      | "TradeCopied"
      | "TradeSkipped"
      | "VaultClosed"
      | "VaultCreated"
      | "VaultDeposited"
      | "VaultPaused"
      | "VaultReopened"
      | "VaultResumed"
      | "VaultWithdrawn"
      | "WatcherRequested"
      | "WatcherResponse"
  ): EventFragment;

  encodeFunctionData(functionFragment: "AUSD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MAX_SLIPPAGE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_TRADE_AGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_COPY_SCORE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_SLIPPAGE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_TRADE_AUSD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addToAllowlist",
    values: [AddressLike, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "closePosition",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createVault",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike[],
      VaultManager.VaultLimitsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "dex", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "executeCopyTrade",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "followerVaults",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllowlist",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFollowerVaults",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFreeBalance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOpenPositions",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUnrealizedPnL",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVault",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "keeperOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "latestPrice",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauseVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "positions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeFromAllowlist",
    values: [AddressLike, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "reopenVault",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike[],
      VaultManager.VaultLimitsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "resumeVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setDex", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "setKeeper",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPrice",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultId",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultPositions",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "vaults", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "AUSD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_SLIPPAGE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_TRADE_AGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_COPY_SCORE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_SLIPPAGE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_TRADE_AUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addToAllowlist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dex", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeCopyTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "followerVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllowlist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFollowerVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFreeBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOpenPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnrealizedPnL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "keeperOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "latestPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pauseVault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "positions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeFromAllowlist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reopenVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resumeVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setDex", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setKeeper", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setOracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vaultId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "vaultPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vaults", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace AllowlistAddedEvent {
  export type InputTuple = [vaultId: BytesLike, tokens: AddressLike[]];
  export type OutputTuple = [vaultId: string, tokens: string[]];
  export interface OutputObject {
    vaultId: string;
    tokens: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AllowlistRemovedEvent {
  export type InputTuple = [vaultId: BytesLike, tokens: AddressLike[]];
  export type OutputTuple = [vaultId: string, tokens: string[]];
  export interface OutputObject {
    vaultId: string;
    tokens: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DexSetEvent {
  export type InputTuple = [dex: AddressLike];
  export type OutputTuple = [dex: string];
  export interface OutputObject {
    dex: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KeeperSetEvent {
  export type InputTuple = [follower: AddressLike, keeper: AddressLike];
  export type OutputTuple = [follower: string, keeper: string];
  export interface OutputObject {
    follower: string;
    keeper: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleSetEvent {
  export type InputTuple = [oracle: AddressLike];
  export type OutputTuple = [oracle: string];
  export interface OutputObject {
    oracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionClosedEvent {
  export type InputTuple = [
    positionId: BytesLike,
    vaultId: BytesLike,
    pnl: BigNumberish,
    exitPrice: BigNumberish
  ];
  export type OutputTuple = [
    positionId: string,
    vaultId: string,
    pnl: bigint,
    exitPrice: bigint
  ];
  export interface OutputObject {
    positionId: string;
    vaultId: string;
    pnl: bigint;
    exitPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionOpenedEvent {
  export type InputTuple = [
    positionId: BytesLike,
    vaultId: BytesLike,
    token: AddressLike,
    ausdAllocated: BigNumberish,
    entryPrice: BigNumberish
  ];
  export type OutputTuple = [
    positionId: string,
    vaultId: string,
    token: string,
    ausdAllocated: bigint,
    entryPrice: bigint
  ];
  export interface OutputObject {
    positionId: string;
    vaultId: string;
    token: string;
    ausdAllocated: bigint;
    entryPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [token: AddressLike, price: BigNumberish];
  export type OutputTuple = [token: string, price: bigint];
  export interface OutputObject {
    token: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategistResponseEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    vaultId: BytesLike,
    score: BigNumberish,
    willExecute: boolean
  ];
  export type OutputTuple = [
    requestId: bigint,
    vaultId: string,
    score: bigint,
    willExecute: boolean
  ];
  export interface OutputObject {
    requestId: bigint;
    vaultId: string;
    score: bigint;
    willExecute: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeCopiedEvent {
  export type InputTuple = [
    vaultId: BytesLike,
    token: AddressLike,
    ausdAllocated: BigNumberish,
    copyScore: BigNumberish
  ];
  export type OutputTuple = [
    vaultId: string,
    token: string,
    ausdAllocated: bigint,
    copyScore: bigint
  ];
  export interface OutputObject {
    vaultId: string;
    token: string;
    ausdAllocated: bigint;
    copyScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeSkippedEvent {
  export type InputTuple = [vaultId: BytesLike, reason: string];
  export type OutputTuple = [vaultId: string, reason: string];
  export interface OutputObject {
    vaultId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultClosedEvent {
  export type InputTuple = [vaultId: BytesLike];
  export type OutputTuple = [vaultId: string];
  export interface OutputObject {
    vaultId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultCreatedEvent {
  export type InputTuple = [
    follower: AddressLike,
    leader: AddressLike,
    vaultId: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    follower: string,
    leader: string,
    vaultId: string,
    amount: bigint
  ];
  export interface OutputObject {
    follower: string;
    leader: string;
    vaultId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultDepositedEvent {
  export type InputTuple = [vaultId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [vaultId: string, amount: bigint];
  export interface OutputObject {
    vaultId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultPausedEvent {
  export type InputTuple = [vaultId: BytesLike];
  export type OutputTuple = [vaultId: string];
  export interface OutputObject {
    vaultId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultReopenedEvent {
  export type InputTuple = [
    follower: AddressLike,
    leader: AddressLike,
    vaultId: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    follower: string,
    leader: string,
    vaultId: string,
    amount: bigint
  ];
  export interface OutputObject {
    follower: string;
    leader: string;
    vaultId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultResumedEvent {
  export type InputTuple = [vaultId: BytesLike];
  export type OutputTuple = [vaultId: string];
  export interface OutputObject {
    vaultId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultWithdrawnEvent {
  export type InputTuple = [vaultId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [vaultId: string, amount: bigint];
  export interface OutputObject {
    vaultId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WatcherRequestedEvent {
  export type InputTuple = [requestId: BigNumberish, vaultId: BytesLike];
  export type OutputTuple = [requestId: bigint, vaultId: string];
  export interface OutputObject {
    requestId: bigint;
    vaultId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WatcherResponseEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    vaultId: BytesLike,
    tokenOut: AddressLike,
    usdValue: BigNumberish,
    tradeTimestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    vaultId: string,
    tokenOut: string,
    usdValue: bigint,
    tradeTimestamp: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    vaultId: string;
    tokenOut: string;
    usdValue: bigint;
    tradeTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VaultManager extends BaseContract {
  connect(runner?: ContractRunner | null): VaultManager;
  waitForDeployment(): Promise<this>;

  interface: VaultManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  AUSD: TypedContractMethod<[], [string], "view">;

  MAX_SLIPPAGE_BPS: TypedContractMethod<[], [bigint], "view">;

  MAX_TRADE_AGE: TypedContractMethod<[], [bigint], "view">;

  MIN_COPY_SCORE: TypedContractMethod<[], [bigint], "view">;

  MIN_SLIPPAGE_BPS: TypedContractMethod<[], [bigint], "view">;

  MIN_TRADE_AUSD: TypedContractMethod<[], [bigint], "view">;

  addToAllowlist: TypedContractMethod<
    [leader: AddressLike, tokens: AddressLike[]],
    [void],
    "nonpayable"
  >;

  closePosition: TypedContractMethod<
    [positionId: BytesLike],
    [void],
    "nonpayable"
  >;

  createVault: TypedContractMethod<
    [
      leader: AddressLike,
      amount: BigNumberish,
      riskLevel: BigNumberish,
      maxPerTradePct: BigNumberish,
      allowlist: AddressLike[],
      limits: VaultManager.VaultLimitsStruct
    ],
    [void],
    "nonpayable"
  >;

  deposit: TypedContractMethod<
    [leader: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  dex: TypedContractMethod<[], [string], "view">;

  executeCopyTrade: TypedContractMethod<
    [
      follower: AddressLike,
      leader: AddressLike,
      tokenOut: AddressLike,
      usdValue: BigNumberish,
      tradePrice: BigNumberish,
      tradeTimestamp: BigNumberish,
      score: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  followerVaults: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getAllowlist: TypedContractMethod<
    [follower: AddressLike, leader: AddressLike],
    [string[]],
    "view"
  >;

  getFollowerVaults: TypedContractMethod<
    [follower: AddressLike],
    [string[]],
    "view"
  >;

  getFreeBalance: TypedContractMethod<
    [follower: AddressLike, leader: AddressLike],
    [bigint],
    "view"
  >;

  getOpenPositions: TypedContractMethod<
    [follower: AddressLike, leader: AddressLike],
    [string[]],
    "view"
  >;

  getUnrealizedPnL: TypedContractMethod<
    [follower: AddressLike, leader: AddressLike],
    [bigint],
    "view"
  >;

  getVault: TypedContractMethod<
    [follower: AddressLike, leader: AddressLike],
    [VaultManager.VaultConfigStructOutput],
    "view"
  >;

  keeperOf: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  latestPrice: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  oracle: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pauseVault: TypedContractMethod<[leader: AddressLike], [void], "nonpayable">;

  positions: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        follower: string;
        leader: string;
        vaultId: string;
        token: string;
        ausdAllocated: bigint;
        tokenAmount: bigint;
        entryPrice: bigint;
        exitPrice: bigint;
        pnl: bigint;
        status: bigint;
        openedAt: bigint;
        closedAt: bigint;
      }
    ],
    "view"
  >;

  removeFromAllowlist: TypedContractMethod<
    [leader: AddressLike, tokens: AddressLike[]],
    [void],
    "nonpayable"
  >;

  reopenVault: TypedContractMethod<
    [
      leader: AddressLike,
      amount: BigNumberish,
      riskLevel: BigNumberish,
      maxPerTradePct: BigNumberish,
      allowlist: AddressLike[],
      limits: VaultManager.VaultLimitsStruct
    ],
    [void],
    "nonpayable"
  >;

  resumeVault: TypedContractMethod<[leader: AddressLike], [void], "nonpayable">;

  setDex: TypedContractMethod<[_dex: AddressLike], [void], "nonpayable">;

  setKeeper: TypedContractMethod<[keeper: AddressLike], [void], "nonpayable">;

  setOracle: TypedContractMethod<[_oracle: AddressLike], [void], "nonpayable">;

  setPrice: TypedContractMethod<
    [token: AddressLike, price: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  vaultId: TypedContractMethod<
    [follower: AddressLike, leader: AddressLike],
    [string],
    "view"
  >;

  vaultPositions: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  vaults: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        VaultManager.VaultLimitsStructOutput
      ] & {
        follower: string;
        leader: string;
        ausdLocked: bigint;
        ausdAllocated: bigint;
        riskLevel: bigint;
        maxPerTradePct: bigint;
        status: bigint;
        limits: VaultManager.VaultLimitsStructOutput;
      }
    ],
    "view"
  >;

  withdraw: TypedContractMethod<[leader: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "AUSD"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_SLIPPAGE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_TRADE_AGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_COPY_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_SLIPPAGE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_TRADE_AUSD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addToAllowlist"
  ): TypedContractMethod<
    [leader: AddressLike, tokens: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "closePosition"
  ): TypedContractMethod<[positionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createVault"
  ): TypedContractMethod<
    [
      leader: AddressLike,
      amount: BigNumberish,
      riskLevel: BigNumberish,
      maxPerTradePct: BigNumberish,
      allowlist: AddressLike[],
      limits: VaultManager.VaultLimitsStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [leader: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dex"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "executeCopyTrade"
  ): TypedContractMethod<
    [
      follower: AddressLike,
      leader: AddressLike,
      tokenOut: AddressLike,
      usdValue: BigNumberish,
      tradePrice: BigNumberish,
      tradeTimestamp: BigNumberish,
      score: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "followerVaults"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllowlist"
  ): TypedContractMethod<
    [follower: AddressLike, leader: AddressLike],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFollowerVaults"
  ): TypedContractMethod<[follower: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getFreeBalance"
  ): TypedContractMethod<
    [follower: AddressLike, leader: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOpenPositions"
  ): TypedContractMethod<
    [follower: AddressLike, leader: AddressLike],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUnrealizedPnL"
  ): TypedContractMethod<
    [follower: AddressLike, leader: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVault"
  ): TypedContractMethod<
    [follower: AddressLike, leader: AddressLike],
    [VaultManager.VaultConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "keeperOf"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "latestPrice"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pauseVault"
  ): TypedContractMethod<[leader: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "positions"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        follower: string;
        leader: string;
        vaultId: string;
        token: string;
        ausdAllocated: bigint;
        tokenAmount: bigint;
        entryPrice: bigint;
        exitPrice: bigint;
        pnl: bigint;
        status: bigint;
        openedAt: bigint;
        closedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeFromAllowlist"
  ): TypedContractMethod<
    [leader: AddressLike, tokens: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reopenVault"
  ): TypedContractMethod<
    [
      leader: AddressLike,
      amount: BigNumberish,
      riskLevel: BigNumberish,
      maxPerTradePct: BigNumberish,
      allowlist: AddressLike[],
      limits: VaultManager.VaultLimitsStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resumeVault"
  ): TypedContractMethod<[leader: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDex"
  ): TypedContractMethod<[_dex: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setKeeper"
  ): TypedContractMethod<[keeper: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOracle"
  ): TypedContractMethod<[_oracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPrice"
  ): TypedContractMethod<
    [token: AddressLike, price: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vaultId"
  ): TypedContractMethod<
    [follower: AddressLike, leader: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "vaultPositions"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "vaults"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        VaultManager.VaultLimitsStructOutput
      ] & {
        follower: string;
        leader: string;
        ausdLocked: bigint;
        ausdAllocated: bigint;
        riskLevel: bigint;
        maxPerTradePct: bigint;
        status: bigint;
        limits: VaultManager.VaultLimitsStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[leader: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AllowlistAdded"
  ): TypedContractEvent<
    AllowlistAddedEvent.InputTuple,
    AllowlistAddedEvent.OutputTuple,
    AllowlistAddedEvent.OutputObject
  >;
  getEvent(
    key: "AllowlistRemoved"
  ): TypedContractEvent<
    AllowlistRemovedEvent.InputTuple,
    AllowlistRemovedEvent.OutputTuple,
    AllowlistRemovedEvent.OutputObject
  >;
  getEvent(
    key: "DexSet"
  ): TypedContractEvent<
    DexSetEvent.InputTuple,
    DexSetEvent.OutputTuple,
    DexSetEvent.OutputObject
  >;
  getEvent(
    key: "KeeperSet"
  ): TypedContractEvent<
    KeeperSetEvent.InputTuple,
    KeeperSetEvent.OutputTuple,
    KeeperSetEvent.OutputObject
  >;
  getEvent(
    key: "OracleSet"
  ): TypedContractEvent<
    OracleSetEvent.InputTuple,
    OracleSetEvent.OutputTuple,
    OracleSetEvent.OutputObject
  >;
  getEvent(
    key: "PositionClosed"
  ): TypedContractEvent<
    PositionClosedEvent.InputTuple,
    PositionClosedEvent.OutputTuple,
    PositionClosedEvent.OutputObject
  >;
  getEvent(
    key: "PositionOpened"
  ): TypedContractEvent<
    PositionOpenedEvent.InputTuple,
    PositionOpenedEvent.OutputTuple,
    PositionOpenedEvent.OutputObject
  >;
  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "StrategistResponse"
  ): TypedContractEvent<
    StrategistResponseEvent.InputTuple,
    StrategistResponseEvent.OutputTuple,
    StrategistResponseEvent.OutputObject
  >;
  getEvent(
    key: "TradeCopied"
  ): TypedContractEvent<
    TradeCopiedEvent.InputTuple,
    TradeCopiedEvent.OutputTuple,
    TradeCopiedEvent.OutputObject
  >;
  getEvent(
    key: "TradeSkipped"
  ): TypedContractEvent<
    TradeSkippedEvent.InputTuple,
    TradeSkippedEvent.OutputTuple,
    TradeSkippedEvent.OutputObject
  >;
  getEvent(
    key: "VaultClosed"
  ): TypedContractEvent<
    VaultClosedEvent.InputTuple,
    VaultClosedEvent.OutputTuple,
    VaultClosedEvent.OutputObject
  >;
  getEvent(
    key: "VaultCreated"
  ): TypedContractEvent<
    VaultCreatedEvent.InputTuple,
    VaultCreatedEvent.OutputTuple,
    VaultCreatedEvent.OutputObject
  >;
  getEvent(
    key: "VaultDeposited"
  ): TypedContractEvent<
    VaultDepositedEvent.InputTuple,
    VaultDepositedEvent.OutputTuple,
    VaultDepositedEvent.OutputObject
  >;
  getEvent(
    key: "VaultPaused"
  ): TypedContractEvent<
    VaultPausedEvent.InputTuple,
    VaultPausedEvent.OutputTuple,
    VaultPausedEvent.OutputObject
  >;
  getEvent(
    key: "VaultReopened"
  ): TypedContractEvent<
    VaultReopenedEvent.InputTuple,
    VaultReopenedEvent.OutputTuple,
    VaultReopenedEvent.OutputObject
  >;
  getEvent(
    key: "VaultResumed"
  ): TypedContractEvent<
    VaultResumedEvent.InputTuple,
    VaultResumedEvent.OutputTuple,
    VaultResumedEvent.OutputObject
  >;
  getEvent(
    key: "VaultWithdrawn"
  ): TypedContractEvent<
    VaultWithdrawnEvent.InputTuple,
    VaultWithdrawnEvent.OutputTuple,
    VaultWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "WatcherRequested"
  ): TypedContractEvent<
    WatcherRequestedEvent.InputTuple,
    WatcherRequestedEvent.OutputTuple,
    WatcherRequestedEvent.OutputObject
  >;
  getEvent(
    key: "WatcherResponse"
  ): TypedContractEvent<
    WatcherResponseEvent.InputTuple,
    WatcherResponseEvent.OutputTuple,
    WatcherResponseEvent.OutputObject
  >;

  filters: {
    "AllowlistAdded(bytes32,address[])": TypedContractEvent<
      AllowlistAddedEvent.InputTuple,
      AllowlistAddedEvent.OutputTuple,
      AllowlistAddedEvent.OutputObject
    >;
    AllowlistAdded: TypedContractEvent<
      AllowlistAddedEvent.InputTuple,
      AllowlistAddedEvent.OutputTuple,
      AllowlistAddedEvent.OutputObject
    >;

    "AllowlistRemoved(bytes32,address[])": TypedContractEvent<
      AllowlistRemovedEvent.InputTuple,
      AllowlistRemovedEvent.OutputTuple,
      AllowlistRemovedEvent.OutputObject
    >;
    AllowlistRemoved: TypedContractEvent<
      AllowlistRemovedEvent.InputTuple,
      AllowlistRemovedEvent.OutputTuple,
      AllowlistRemovedEvent.OutputObject
    >;

    "DexSet(address)": TypedContractEvent<
      DexSetEvent.InputTuple,
      DexSetEvent.OutputTuple,
      DexSetEvent.OutputObject
    >;
    DexSet: TypedContractEvent<
      DexSetEvent.InputTuple,
      DexSetEvent.OutputTuple,
      DexSetEvent.OutputObject
    >;

    "KeeperSet(address,address)": TypedContractEvent<
      KeeperSetEvent.InputTuple,
      KeeperSetEvent.OutputTuple,
      KeeperSetEvent.OutputObject
    >;
    KeeperSet: TypedContractEvent<
      KeeperSetEvent.InputTuple,
      KeeperSetEvent.OutputTuple,
      KeeperSetEvent.OutputObject
    >;

    "OracleSet(address)": TypedContractEvent<
      OracleSetEvent.InputTuple,
      OracleSetEvent.OutputTuple,
      OracleSetEvent.OutputObject
    >;
    OracleSet: TypedContractEvent<
      OracleSetEvent.InputTuple,
      OracleSetEvent.OutputTuple,
      OracleSetEvent.OutputObject
    >;

    "PositionClosed(bytes32,bytes32,int256,uint256)": TypedContractEvent<
      PositionClosedEvent.InputTuple,
      PositionClosedEvent.OutputTuple,
      PositionClosedEvent.OutputObject
    >;
    PositionClosed: TypedContractEvent<
      PositionClosedEvent.InputTuple,
      PositionClosedEvent.OutputTuple,
      PositionClosedEvent.OutputObject
    >;

    "PositionOpened(bytes32,bytes32,address,uint256,uint256)": TypedContractEvent<
      PositionOpenedEvent.InputTuple,
      PositionOpenedEvent.OutputTuple,
      PositionOpenedEvent.OutputObject
    >;
    PositionOpened: TypedContractEvent<
      PositionOpenedEvent.InputTuple,
      PositionOpenedEvent.OutputTuple,
      PositionOpenedEvent.OutputObject
    >;

    "PriceUpdated(address,uint256)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;

    "StrategistResponse(uint256,bytes32,uint8,bool)": TypedContractEvent<
      StrategistResponseEvent.InputTuple,
      StrategistResponseEvent.OutputTuple,
      StrategistResponseEvent.OutputObject
    >;
    StrategistResponse: TypedContractEvent<
      StrategistResponseEvent.InputTuple,
      StrategistResponseEvent.OutputTuple,
      StrategistResponseEvent.OutputObject
    >;

    "TradeCopied(bytes32,address,uint256,uint8)": TypedContractEvent<
      TradeCopiedEvent.InputTuple,
      TradeCopiedEvent.OutputTuple,
      TradeCopiedEvent.OutputObject
    >;
    TradeCopied: TypedContractEvent<
      TradeCopiedEvent.InputTuple,
      TradeCopiedEvent.OutputTuple,
      TradeCopiedEvent.OutputObject
    >;

    "TradeSkipped(bytes32,string)": TypedContractEvent<
      TradeSkippedEvent.InputTuple,
      TradeSkippedEvent.OutputTuple,
      TradeSkippedEvent.OutputObject
    >;
    TradeSkipped: TypedContractEvent<
      TradeSkippedEvent.InputTuple,
      TradeSkippedEvent.OutputTuple,
      TradeSkippedEvent.OutputObject
    >;

    "VaultClosed(bytes32)": TypedContractEvent<
      VaultClosedEvent.InputTuple,
      VaultClosedEvent.OutputTuple,
      VaultClosedEvent.OutputObject
    >;
    VaultClosed: TypedContractEvent<
      VaultClosedEvent.InputTuple,
      VaultClosedEvent.OutputTuple,
      VaultClosedEvent.OutputObject
    >;

    "VaultCreated(address,address,bytes32,uint256)": TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;
    VaultCreated: TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;

    "VaultDeposited(bytes32,uint256)": TypedContractEvent<
      VaultDepositedEvent.InputTuple,
      VaultDepositedEvent.OutputTuple,
      VaultDepositedEvent.OutputObject
    >;
    VaultDeposited: TypedContractEvent<
      VaultDepositedEvent.InputTuple,
      VaultDepositedEvent.OutputTuple,
      VaultDepositedEvent.OutputObject
    >;

    "VaultPaused(bytes32)": TypedContractEvent<
      VaultPausedEvent.InputTuple,
      VaultPausedEvent.OutputTuple,
      VaultPausedEvent.OutputObject
    >;
    VaultPaused: TypedContractEvent<
      VaultPausedEvent.InputTuple,
      VaultPausedEvent.OutputTuple,
      VaultPausedEvent.OutputObject
    >;

    "VaultReopened(address,address,bytes32,uint256)": TypedContractEvent<
      VaultReopenedEvent.InputTuple,
      VaultReopenedEvent.OutputTuple,
      VaultReopenedEvent.OutputObject
    >;
    VaultReopened: TypedContractEvent<
      VaultReopenedEvent.InputTuple,
      VaultReopenedEvent.OutputTuple,
      VaultReopenedEvent.OutputObject
    >;

    "VaultResumed(bytes32)": TypedContractEvent<
      VaultResumedEvent.InputTuple,
      VaultResumedEvent.OutputTuple,
      VaultResumedEvent.OutputObject
    >;
    VaultResumed: TypedContractEvent<
      VaultResumedEvent.InputTuple,
      VaultResumedEvent.OutputTuple,
      VaultResumedEvent.OutputObject
    >;

    "VaultWithdrawn(bytes32,uint256)": TypedContractEvent<
      VaultWithdrawnEvent.InputTuple,
      VaultWithdrawnEvent.OutputTuple,
      VaultWithdrawnEvent.OutputObject
    >;
    VaultWithdrawn: TypedContractEvent<
      VaultWithdrawnEvent.InputTuple,
      VaultWithdrawnEvent.OutputTuple,
      VaultWithdrawnEvent.OutputObject
    >;

    "WatcherRequested(uint256,bytes32)": TypedContractEvent<
      WatcherRequestedEvent.InputTuple,
      WatcherRequestedEvent.OutputTuple,
      WatcherRequestedEvent.OutputObject
    >;
    WatcherRequested: TypedContractEvent<
      WatcherRequestedEvent.InputTuple,
      WatcherRequestedEvent.OutputTuple,
      WatcherRequestedEvent.OutputObject
    >;

    "WatcherResponse(uint256,bytes32,address,uint256,uint256)": TypedContractEvent<
      WatcherResponseEvent.InputTuple,
      WatcherResponseEvent.OutputTuple,
      WatcherResponseEvent.OutputObject
    >;
    WatcherResponse: TypedContractEvent<
      WatcherResponseEvent.InputTuple,
      WatcherResponseEvent.OutputTuple,
      WatcherResponseEvent.OutputObject
    >;
  };
}
