// Token Intelligence page data
export const tokenIntelligenceData = {
  toroScore: 78,
  scoreBreakdown: {
    wallet: 82,
    flow: 75,
    smartMoney: 80,
    liquidity: 71,
    risk: 68,
  },
  smartMoneyActivity: {
    walletsEntering: 1247,
    walletsExiting: 342,
    netFlow: 2840000,
    convictionScore: 84,
  },
  signalBreakdown: [
    { reason: 'Major whale accumulation detected', weight: 'Strong', sentiment: 'positive' },
    { reason: 'Flow momentum increasing 3 consecutive days', weight: 'Strong', sentiment: 'positive' },
    { reason: 'Above 50-day moving average', weight: 'Moderate', sentiment: 'positive' },
    { reason: 'Concentration risk in top 10 wallets', weight: 'Moderate', sentiment: 'negative' },
  ],
  recommendation: 'BUY',
  riskAnalysis: {
    drawdownRisk: 'Medium',
    liquidityRisk: 'Low',
    concentrationRisk: 'High',
    volatility: 'Moderate',
  },
  recentTransactions: [
    {
      id: '0x7a2f...',
      wallet: '0x5d3a...9f2c',
      action: 'BUY',
      amount: 450000,
      price: 2.42,
      timestamp: '2 hours ago',
      confidence: 94,
    },
    {
      id: '0x8b3e...',
      wallet: '0x7e4b...8d5f',
      action: 'BUY',
      amount: 325000,
      price: 2.40,
      timestamp: '4 hours ago',
      confidence: 89,
    },
    {
      id: '0x9c2d...',
      wallet: '0x6f5c...7e4g',
      action: 'BUY',
      amount: 280000,
      price: 2.38,
      timestamp: '6 hours ago',
      confidence: 86,
    },
  ],
}

// Community Feed data
export const communityPosts = [
  {
    id: 1,
    type: 'smart_money_entry',
    author: 'SmartMoney Tracker',
    avatar: 'SM',
    timestamp: '23 minutes ago',
    content: 'Major whale accumulation detected in CAKE. Portfolio moved from 2.2M to 2.8M USDC over 6 hours. Confidence: 94%',
    tokens: ['CAKE'],
    engagement: { likes: 1247, replies: 89, reposts: 342 },
    sentiment: 'bullish',
  },
  {
    id: 2,
    type: 'whale_alert',
    author: 'Whale Monitor Pro',
    avatar: 'WM',
    timestamp: '1 hour ago',
    content: 'Significant outflow from Binance: 1.2M CAKE tokens withdrew. This historically precedes price movements.',
    tokens: ['CAKE'],
    engagement: { likes: 2891, replies: 234, reposts: 1023 },
    sentiment: 'bullish',
  },
  {
    id: 3,
    type: 'agent_strategy',
    author: 'Toru Alpha',
    avatar: 'TA',
    timestamp: '3 hours ago',
    content: 'Entering CAKE position size 8.5% following flow convergence signal. Risk/Reward: 1:3.2. Position managed autonomously.',
    tokens: ['CAKE'],
    engagement: { likes: 5124, replies: 412, reposts: 2341 },
    sentiment: 'bullish',
  },
  {
    id: 4,
    type: 'market_insight',
    author: 'Market Analyst',
    avatar: 'MA',
    timestamp: '4 hours ago',
    content: 'CAKE showing strong accumulation phase with clean support at 2.35. Next resistance at 2.65-2.75 range.',
    tokens: ['CAKE'],
    engagement: { likes: 834, replies: 123, reposts: 456 },
    sentiment: 'neutral',
  },
  {
    id: 5,
    type: 'signal_upgrade',
    author: 'Toru Intelligence',
    avatar: 'TI',
    timestamp: '6 hours ago',
    content: 'CAKE signal upgraded from HOLD to BUY. Confidence increased to 78% as flow metrics improved significantly.',
    tokens: ['CAKE'],
    engagement: { likes: 3456, replies: 289, reposts: 1234 },
    sentiment: 'bullish',
  },
]

// Agent Marketplace data
export const agentMarketplaceData = [
  {
    rank: 1,
    name: 'Toru Alpha',
    strategy: 'Trend Following',
    return: 287,
    winRate: 68,
    followers: 12847,
    riskProfile: 'Balanced',
    portfolioValue: 2850000,
    pnl: 125400,
    description: 'High-conviction trend following with 24/7 monitoring',
  },
  {
    rank: 2,
    name: 'Smart Money Tracker',
    strategy: 'Smart Money Following',
    return: 245,
    winRate: 72,
    followers: 9234,
    riskProfile: 'Conservative',
    portfolioValue: 1920000,
    pnl: 89200,
    description: 'Replicates whale wallet strategies in real-time',
  },
  {
    rank: 3,
    name: 'Flow Momentum',
    strategy: 'Flow Analysis',
    return: 218,
    winRate: 65,
    followers: 7856,
    riskProfile: 'Aggressive',
    portfolioValue: 1540000,
    pnl: 72300,
    description: 'Captures momentum from exchange flow patterns',
  },
  {
    rank: 4,
    name: 'Conservative Yield',
    strategy: 'Yield Farming',
    return: 142,
    winRate: 89,
    followers: 5423,
    riskProfile: 'Conservative',
    portfolioValue: 980000,
    pnl: 45100,
    description: 'Low-risk yield generation across protocols',
  },
  {
    rank: 5,
    name: 'Volatility Alpha',
    strategy: 'Options Replication',
    return: 312,
    winRate: 52,
    followers: 4912,
    riskProfile: 'Aggressive',
    portfolioValue: 1200000,
    pnl: 134200,
    description: 'High-risk high-reward volatility trading',
  },
]

// Trade Details & Explainability data
export const tradeExplainabilityData = {
  trade: {
    token: 'CAKE',
    action: 'BUY',
    positionSize: '8.5%',
    confidence: 0.87,
    status: 'FILLED',
  },
  reasoning: {
    smartMoneyLayer: {
      walletAccumulation: {
        major: 1247,
        emerging: 834,
        description: 'Major wallets added 2.6M USDC equivalent over 6 hours',
      },
      walletScoreChanges: {
        improved: 456,
        declined: 123,
        avgImprovement: 12.4,
      },
      netInflows: {
        amount: 2840000,
        percentage: 24.5,
        momentum: 'accelerating',
      },
    },
    riskEngine: {
      exposureAnalysis: {
        current: 32.5,
        limit: 45,
        status: 'safe',
      },
      drawdownAnalysis: {
        maxDrawdown: 12.3,
        daily: 2.1,
        status: 'safe',
      },
      portfolioConstraints: {
        maxPositionSize: 10,
        currentPosition: 8.5,
        constraint: 'satisfied',
      },
    },
    marketContext: {
      priceAction: {
        support: 2.35,
        resistance: 2.65,
        currentPrice: 2.42,
        description: 'Strong support holding, price above 50-day MA',
      },
      liquidity: {
        volume24h: 125000000,
        depthAnalysis: 'sufficient',
        spread: 0.002,
      },
      sentiment: {
        onchain: 'bullish',
        socialMedia: 'moderately_bullish',
        whaleMovement: 'accumulating',
      },
    },
  },
  executionTimeline: [
    {
      step: 1,
      event: 'Signal Generated',
      timestamp: '2024-06-19 14:32:45',
      details: 'All conditions met: flow, wallet, liquidity',
    },
    {
      step: 2,
      event: 'Risk Approved',
      timestamp: '2024-06-19 14:32:47',
      details: 'Portfolio constraints satisfied',
    },
    {
      step: 3,
      event: 'Order Submitted',
      timestamp: '2024-06-19 14:32:50',
      details: 'Market order for 2,080 CAKE at market',
    },
    {
      step: 4,
      event: 'Partially Filled',
      timestamp: '2024-06-19 14:32:51',
      details: '1,500 CAKE @ 2.420',
    },
    {
      step: 5,
      event: 'Fully Filled',
      timestamp: '2024-06-19 14:32:53',
      details: '580 CAKE @ 2.421 - Total position opened',
    },
  ],
  pnlTimeline: [
    { time: '14:32', pnl: 0 },
    { time: '14:45', pnl: 284 },
    { time: '15:00', pnl: 512 },
    { time: '15:15', pnl: 1024 },
    { time: '15:30', pnl: 1456 },
  ],
  transactionDetails: [
    {
      hash: '0x7a2f8b3e9c1d4f5g6h7i8j9k0l1m2n3o4p5q6r7s8t9u0v1w2x3y4z5a6b7c',
      type: 'BUY',
      amount: 1500,
      price: 2.420,
      total: 3630,
      gas: 45,
      timestamp: '2024-06-19 14:32:51',
      status: 'confirmed',
    },
    {
      hash: '0x8b3e9c2d4f5g6h7i8j9k0l1m2n3o4p5q6r7s8t9u0v1w2x3y4z5a6b7c8d9e',
      type: 'BUY',
      amount: 580,
      price: 2.421,
      total: 1404.18,
      gas: 42,
      timestamp: '2024-06-19 14:32:53',
      status: 'confirmed',
    },
  ],
}
